### ISSUE TITLE
Support 1.2 package contents

### ISSUE THREAD

**Issue by lassombra** [francocatena/meteor-compass#9]
Please update to support 1.2 style package exports ex: https://atmospherejs.com/reywood/bootstrap3-sass

**Comment by francocatena** [comment]
Hi @lassombra, it's done. Thanks for the link =)

Be aware of the new syntax:

``` scss
@import "{francocatena:compass}/compass";
```

Try it and let me know any issues.

Cheers.
